apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy-svc
  labels:
    app: nginx-reverse-proxy
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-reverse-proxy
  type: ClusterIP # Or LoadBalancer if you need external access