apiVersion: v1
kind: Service
metadata:
  name: my-app-2-svc
  labels:
    app: my-app-2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-app-2
  type: ClusterIP